apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-cloud-scheduler
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-cloud-scheduler
    source:
      repo: /usr/local/google/home/ssranya/terraform-google-cloud-scheduler/terraform-google-cloud-scheduler
    version: 0.0.1
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description:
      preDeploy: To deploy this blueprint you must have an active billing account and billing permissions.
    icon: assets/icon.png
    costEstimate:
      description: Blueprint cost details
      url: https://cloud.google.com/products/calculator?id=02fb0c45-cc29-4567-8cc6-f72ac9024add
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: name
        description: The name of the job
        varType: string
        required: true
      - name: project_id
        description: The project ID to deploy to
        varType: string
        required: true
      - name: location
        description: Region where the scheduler job resides
        varType: string
        required: true
      - name: schedule
        description: Schedule on which the job will be executed
        varType: string
        required: true
      - name: attempt_deadline
        description: The deadline for job attempts
        varType: string
        required: true
      - name: retry_config
        description: If a job does not complete successfully, then it will be retried with exponential backoff
        varType: |-
          object({
              retry_count          = optional(number)
              max_retry_duration   = optional(string)
              min_backoff_duration = optional(string)
              max_backoff_duration = optional(string)
              max_doublings        = optional(number)
            })
        required: true
      - name: app_engine_http_target
        description: App Engine HTTP target. If the job providers a App Engine HTTP target the cron will send a request to the service instance
        varType: |-
          object({
              http_method = optional(string)
              app_engine_routing = optional(object({
                service = optional(string)
                version = optional(string)
                instance = optional(string)
              }))
              relative_uri = optional(string)
              body = optional(string)
              headers = optional(object({
                    name  = string
                    value = string
                  }), null)
            })
        required: true
      - name: description
        description: A human-readable description for the job
        varType: string
      - name: time_zone
        description: Specifies the time zone to be used in interpreting schedule
        varType: string
        defaultValue: UTC
      - name: paused
        description: Sets the job to a paused state
        varType: bool
        defaultValue: false
      - name: pubsub_target
        description: Pub/Sub target If the job providers a Pub/Sub target the cron will publish a message to the provided topic
        varType: |-
          object({
              topic_name = string
              data       = optional(string)
              attributes = optional(list(string))
            })
      - name: http_target
        description: If the job providers a http_target the cron will send a request to the targeted url
        varType: |-
          object({
              uri = string
              http_method = optional(string)
              body = optional(string)
              oath_token = optional(object({
                service_account_email = string
                scope = optional(string)
              }))
              oidc_token = optional(object({
                service_account_email = string
                audience = optional(string)
              }))
            })
    outputs:
      - name: id
        description: An identifier for the resource
      - name: state
        description: State of the job
  requirements:
    roles:
      - level: Project
        roles:
          - roles/iam.serviceAccountAdmin
          - roles/iam.serviceAccountUser
          - roles/resourcemanager.projectIamAdmin
          - roles/serviceusage.serviceUsageAdmin
          - roles/cloudscheduler.admin
    services:
      - cloudresourcemanager.googleapis.com
      - cloudscheduler.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 3.53, < 7"
